#include <stdio.h>
/*
GOOGLE GEMINI:
- Your task is to correct this function. There are several valid ways to solve this problem in C.
- Rewrite the get_error_message function to correctly and safely return the error string. 
- Please provide at least two different, correct solutions. This will demonstrate your breadth of knowledge.
*/

#define CODE_ENABLE 2

#if CODE_ENABLE == 0
//Starting point generated by Gemini for this exercise

/**
 * @brief This function incorrectly returns a pointer to a local variable.
 * @param error_code The error code to translate.
 * @return A pointer to an error message string.
 */
char* get_error_message(int error_code) {
    // This array is created on the stack and is destroyed when the function returns.
    char message[] = "Error: Invalid Input";

    if (error_code == 1) {
        // Returning a pointer to 'message' is the error.
        return message;
    }

    return NULL;
}
#elif CODE_ENABLE == 1
//Solution 1:  Using static, I can make the array move from the stack into the initialised data segment part of memory
//             thus allowing persistence, even when the function returns to the caller.

char* get_error_message(int error_code) {
    static char message[] = "Error: Invalid Input";

    if (error_code == 1) {
        return message;
    }

    return NULL;
}

#elif CODE_ENABLE == 2
//Solution 2:  Have the string literal in read only memory, which persists until program termination
char* get_error_message(int error_code) {
    //Compiler complains that I need `const char*`, but to keep things simple
    //and satisfy compiler and not expanding complexity of caller `main()`, just
    //typecast to indicate to compiler "I know what I'm doing"!
    char* message = (char*)"Error: Invalid Input";

    if (error_code == 1) {
        return message;
    }

    return NULL;
}

#endif

int main() {
    printf("Attempting to get an error message...\n");
    char* error_str = get_error_message(1);

    if (error_str != NULL) {
        // This will cause undefined behavior (likely a crash or garbage output).
        printf("Message from function: %s\n", error_str);
    }
    else {
        printf("No message returned.\n");
    }

    return 0;
}
